myTextbox = noone;

myText[0] = "In a fire emergency, a hot door knob serves as a critical indicator of potential danger on the other side of a door.\n The intense heat generated by a fire can cause metal surfaces, including door knobs, to become extremely hot.\n Checking the temperature of a door knob before opening it is a crucial safety measure during evacuation.\n\nPress enter to continue";
myText[1] = "Now look for a tool to destroy the door.\n\nPress enter to continue"